### ISSUE TITLE
Shorter Functions

### ISSUE THREAD

**Issue by ersinesen** [msharp/elixir-statistics#14]
Here are shorter versions of some of the Match functions:

  def median(list) do
    Enum.sort(list) |> Enum.at(round(Float.floor(length(list)/2)))
  end

  def hist(list) do
    list |> Enum.reduce(%{}, fn(tag, acc) -> Map.update(acc, tag, 1, &(&1 + 1)) end)
  end

  def mode(list) do
    h = hist(list)
    max = Map.values(h) |> Enum.max()
    h |> Enum.find(fn {key,val} -> val == max end) |> elem(0)
  end

  @spec factorial(non_neg_integer) :: non_neg_integer
  def factorial(n) when n < 0 do
    raise ArithmeticError, message: "Argument n must be a positive number"
  end
  def factorial(n) when n == 0 or n == 1 do
    1
  end
  def factorial(n) do
    n*factorial(n-1)
  end

**Comment by msharp** [comment]
thanks @ersinesen 

I like the `hist\1` function as a step toward `mode`. If there was a public `hist` function, it could be useful if it also allowed a `buckets` parameter to generate data ready for a histogram.

do you want to make a PR?

**Comment by ersinesen** [comment]
You can replace any of the functions as you wish. I have not done a pull request before, I dont know the procedure.

**Comment by msharp** [comment]
updated some functions based on @ersinesen suggestions
