### ISSUE TITLE
Mode calculation (samples without modes + and multi-mode)

### ISSUE THREAD

**Issue by PragTob** [msharp/elixir-statistics#22]
Hi there!

Thanks for providing a numbers and statistics library!

I think I might have found a little bug/edge case in the mode calculations:

```elixir
iex(7)> Statistics.mode([1, 2, 3])        
1 # should be nil to the best of my knowledge as nothing occurs more than once
iex(8)> Statistics.mode([1, 2, 2, 3, 3])  
2 # should be [2, 3] as 2 values occur multiple times
```

[Mode at Wikipedia](https://en.wikipedia.org/wiki/Mode_(statistics))
> Given the list of data [1, 1, 2, 4, 4] the mode is not unique – the dataset may be said to be bimodal, while a set with more than two modes may be described as multimodal. 

I can't find a good source of no mode if no values occurs most often right now.

For reference here's how [statistex determines the mode](https://github.com/bencheeorg/statistex/blob/master/lib/statistex/mode.ex#L25-L50) (which arguably might be a bit verbose :woman_shrugging: )

**Comment by msharp** [comment]
Thanks @PragTob 

Would you like to submit a pull request to resolve this issue?

**Comment by PragTob** [comment]
Hi there,

truth be told I'm not really using - I was looking at the library when evaluating if it was worth releasing my statistics library (Statistex) and came across this so I thought I might as well report it as I believe it to be a bug.

That said, I'm not the one to argue with numpy and scipy. It's just what I read up on when implementing mode (or fully truthful, what someone else read up on and I questioned when reviewing it :) )

I think it's important to know about a data set that there are multiple modes and also seeing them as they might be very interesting. For instance I use this mostly with benchmarking. Seeing that there are 2 modes but they aren't directly "next" to each other is super interesting.

In the same vein, when no value occurs more than once and then just the smallest value is reported that seems highly unhelpful to me. In benchmarking terms it would have me believe that the fastest run time is the one that occurs most frequently which imo heavily skews the results.

Anyhow, that's just my perspective/what I remember from reading it up back then. If numpy and scipy do it like this I'm sure it's fine and feel free to close this :)

Tobi

**Comment by msharp** [comment]
Thanks for the background @PragTob 

To be honest, I probably didn't think too much about the `mode` implementation.  It's not a statistic I use very often.

Benchmarking is probably better evaluated with percentiles anyway, especially if you have real (floating point) numbers.

There might be scope for another `mode` function with a different arity which can support multimodal datasets.

**Comment by PragTob** [comment]
I find all of them useful, but yes benchee also supports percentiles :) (Currently by default shows 99th%, which might be too hardcore maybe 95th% would be a better default, not sure) But yeah, love me some box plots :)
