### ISSUE TITLE
Would be interesting to use rustler or Numbat for better performance

### ISSUE THREAD

**Issue by sonic182** [msharp/elixir-statistics#25]
How about translate the code to a rustler extension? https://github.com/rusterlium/rustler I know will not be faster as C but It may be faster to code.

**Comment by msharp** [comment]
Yes, it would probably be faster.

I'd love to see a pull request if you were interested in implementing some of the slower parts.  For example a resolution of #3

**Comment by cultofmetatron** [comment]
now that numbat is out, it might be better to use that for the calculations where applicable

**Comment by msharp** [comment]
Doesn't look like Numbat has a release on Hex.pm yet.  Current version in GH is `0.1.0-dev`.

Does look like it will provide replacements for many of `Statistics`' functions.  It would be nice to see a PR that incorporates Numbat, and perhaps some of the slower distribution functions can be improved.

**Comment by msharp** [comment]
> How about using Nx for the calculations? https://hex.pm/packages/nx

Yes, definitely. This library predates Nx and a large chunk of it is now basically redundant. I'd love to update it to use Nx underneath and continue to provide a simple stats-focused api. Time is an issue though, so I'd welcome any help.

**Comment by msharp** [comment]
Will start to adopt Nx in [v0.7](https://github.com/msharp/elixir-statistics/tree/v0.7)
