### ISSUE TITLE
Statistics.mean behaviour when passed an empty list

### ISSUE THREAD

**Issue by knrz** [msharp/elixir-statistics#8]
Would it make sense to return `nil` instead of throwing?

**Comment by msharp** [comment]
Good question. 

I'm discovering Elixir whilst building this library so I am not sure what the most idiomatic pattern is.

If I were to do this for `mean`, I should also implement an empty_list -> nil case for every other function that takes a list argument (median, mode, etc...)

Can you point to any Elixir code or a style guide that advocates a similar pattern?

**Comment by knrz** [comment]
Interesting thing.

Checking out the [Elixir source code for the List module](https://github.com/elixir-lang/elixir/blob/v1.0.5/lib/elixir/lib/list.ex#L135), `List.first` and `List.last` have a dedicated branch for an empty list.

But also, checking out the [source for the Enum module](https://github.com/elixir-lang/elixir/blob/v1.0.5/lib/elixir/lib/enum.ex#L1166), `Enum.min_by` and `Enum.max_by` both throw a specialized error when passed an empty list.

Maybe, I dunno, we could have the bang version of the function (`mean!`) which can through `Statistics.EmptySetError` or something) and the non-bang version (`mean`) that just returns `nil`.

//I'd be happy to try my hand at implementing it.

**Comment by msharp** [comment]
Thanks for that. Interesting.

I'd lean towards returning `nil` rather than raising an error (conceptually, the mean of an empty list is nothing, right?). 

I haven't seen bang methods being widely used in Elixir - but I'm learning as I go.

If you want to submit a pull request, I'd gladly accept it.

**Comment by msharp** [comment]
Thanks for the PR @knrz - I've merged it and published v0.3.0 to hex.pm
